"""Table Task edits

Revision ID: 32fc8f4b2f6a
Revises: e2c98b59540c
Create Date: 2025-02-12 21:15:04.392003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32fc8f4b2f6a"
down_revision: Union[str, None] = "e2c98b59540c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
