"""Table Task edits

Revision ID: 84b28c3b6224
Revises: 7ce3204a5bbe
Create Date: 2025-02-12 20:26:37.499547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84b28c3b6224"
down_revision: Union[str, None] = "7ce3204a5bbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_task_id"), "task", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_task_id"), "task", type_="unique")
    # ### end Alembic commands ###
