"""Models relationship

Revision ID: d739e72c0d84
Revises: 31f04252f75d
Create Date: 2025-02-09 13:41:25.227353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd739e72c0d84'
down_revision: Union[str, None] = '31f04252f75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_task_id'), 'task', ['id'])
    op.create_foreign_key(op.f('fk_task_user_id_user'), 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_user_id_user'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('uq_task_id'), 'task', type_='unique')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
